Fix compile warnings in client/ and lib/.
BOINC/boinc pull request #4206
Opened 2021-02-19 06:10 UTC by davidpanderson

Check returns from fgets(), sscanf() etc.
Use %.*s to fix truncation warnings.
Fix code formatting.
Fix Makefile.linux

2021-02-21 02:25 UTC, AenBleidd requested changes

2021-03-12 05:41 UTC, davidpanderson commented
@AenBleidd, please review

2021-03-12 13:52 UTC, AenBleidd commented
Looks good to me. Thanks!

2021-03-12 13:52 UTC, AenBleidd approved these changes

2021-03-12 13:52 UTC, merged