[Android] Fix counter is up on retry transfer
BOINC/boinc pull request #4355
Opened 2021-04-30 22:48 UTC by talregev

Fixes #3928
implement cpp code:
https://github.com/BOINC/boinc/blob/b2b790e6d740a811d25bf58ecc3dc7fe067602a6/clientgui/ViewTransfers.cpp#L851-L868

2021-04-30 22:59 UTC, talregev commented
Example when internet is cut off: 

![image](https://user-images.githubusercontent.com/7043539/116761582-b9559080-aa20-11eb-88a9-9caaf0c0bd07.png)

2021-05-01 14:37 UTC, AenBleidd requested changes

2021-05-01 14:37 UTC, AenBleidd commented on android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/Transfer.kt
> +    ERR_GIVEUP_UPLOAD(-115),
extra coma is not needed

2021-05-01 14:59 UTC, talregev commented on android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/Transfer.kt
> +    ERR_GIVEUP_UPLOAD(-115),
done

2021-05-01 15:11 UTC, AenBleidd approved these changes

2021-05-01 15:34 UTC, merged