Disable new version check
BOINC/boinc pull request #4616
Opened 2022-01-28 21:45 UTC by LocutusOfBorg

followup PR after https://github.com/BOINC/boinc/pull/4272

2022-01-30 08:33 UTC, LocutusOfBorg commented
note: I don't know how to test because I didn't yet figure out how the parsing works (and how to change the xml file)

2022-02-05 02:37 UTC, talregev commented
copy this xml:
https://github.com/BOINC/boinc/blob/master/android/BOINC/app/src/main/assets/cc_config.xml

add these lines:

```xml
 <disable_version_check>1</disable_version_check>
```

2022-02-07 21:45 UTC, LocutusOfBorg commented
well so my conf file was correct...
cat /etc/boinc-client/cc_config.xml
```
<!--
This is a minimal configuration file cc_config.xml of the BOINC core client.
For a complete list of all available options and logging flags and their
meaning see: https://boinc.berkeley.edu/wiki/client_configuration
-->
<cc_config>
  <log_flags>
    <task>1</task>
    <file_xfer>1</file_xfer>
    <sched_ops>1</sched_ops>
  </log_flags>
  <options>
    <disable_version_check>1</disable_version_check>
  </options>
</cc_config>
```

but for some reasons I still see the "update" mechanism shown...

2022-02-07 22:19 UTC, LocutusOfBorg commented
I'm debugging the parser code

2022-02-08 19:35 UTC, talregev commented
I think you need to delete the  xml you copy.
 let boinc create one by default, the search for it, and edit with correct option.
Then you understand what to do.

2022-02-11 23:11 UTC, AenBleidd requested changes

2022-02-11 23:11 UTC, AenBleidd commented on lib/cc_config.cpp
> +        if (xp.parse_bool("disable_version_check", disable_version_check)) continue;
You already parsed this flag on the line 322

2022-03-03 18:44 UTC, talregev commented
@LocutusOfBorg Do you need some help?

2024-03-06 22:22 UTC, AenBleidd commented
Since we have now a CI flow that builds the linux packages for 4 different Linux distros (for more details see https://github.com/BOINC/boinc/wiki/Linux-DEB-and-RPM-support), and we also want to encourage our users to use the latest version of our software, there is no reason to implement this functionality.
For the distros we're currently missing, it's quite easy to add them and publish the same way from the BOINC official web-site (and this is something we are gonna do).
Thus, I'm closing this PR without merge.

2024-03-06 22:22 UTC, closed without merging