Remove unused variables from #4897 and #4912
BOINC/boinc pull request #4942
Opened 2022-09-30 18:32 UTC by Vulpine05

Code cleanup of unused variables as a result of #4897 and #4912.  Thank you, @CharlieFenton for the catch, apologizes for the sloppy work.

2022-09-30 18:54 UTC, AenBleidd approved these changes

2022-09-30 18:55 UTC, AenBleidd requested changes
Build is failed. @Vulpine05, please take a look

2022-09-30 19:08 UTC, Vulpine05 commented
> Build is failed. @Vulpine05, please take a look

I see now.  It should be fixed.  If not I will have to look at it later tonight.

2022-09-30 19:42 UTC, AenBleidd approved these changes

2022-09-30 19:45 UTC, AenBleidd commented
Looks fine to me now.
@CharlieFenton, since this was your request, please make a review as well.
Thank you in advance

2022-09-30 21:54 UTC, CharlieFenton commented
I will review after I get home after the weekend

2022-10-03 09:07 UTC, CharlieFenton approved these changes
Looks good to me. @Vulpine05 Thank you for fixing this.

2022-10-03 09:08 UTC, merged