coproc.cpp: fix include order
BOINC/boinc pull request #5084
Opened 2023-02-05 10:19 UTC by CyberTailor

Compilation fails if "filesys.h" is included after "boinc_fcgi.h".

I don't know what's the reason but here's error message:

```
In file included from /usr/include/features.h:490,
                 from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/stdio.h:27,
                 from /usr/include/fcgi_stdio.h:18,
                 from boinc_fcgi.h:19,
                 from coproc.cpp:22:
/usr/include/wchar.h:582:24: error: 'malloc' attribute argument 1 is ambiguous
  582 |   __attribute_malloc__ __attr_dealloc_fclose;
      |                        ^~~~~~~~~~~~~~~~~~~~~
/usr/include/wchar.h:582:24: note: use a cast to the expected type to disambiguate
```

2023-02-05 11:07 UTC, AenBleidd requested changes
Please specify os and compiler version where you see this error.

2023-02-05 11:07 UTC, AenBleidd commented on lib/coproc.cpp
> +#ifdef _USING_FCGI_
Previously this piece of code was for non '_WIN32' only.
Could you please keep it?

2023-02-05 11:18 UTC, CyberTailor commented
> Please specify os and compiler version where you see this error.

Linux
GCC 12.2.1
Glibc 2.36

2023-02-05 13:53 UTC, AenBleidd commented
There is at least one more place that is failing with the same issue: `lib/filesys.cpp`
Could you please fix that as well?
Ref:
- https://github.com/BOINC/boinc/actions/runs/4096879926/jobs/7064842121
- https://github.com/BOINC/boinc/actions/runs/4096879926/jobs/7064842000

And to test this fix please change this line https://github.com/BOINC/boinc/blob/aa31e3d2f8d7d8edfef1142f45d136dcd7fb870b/.github/workflows/linux.yml#L22
to `runs-on: ubuntu-latest`

2023-02-06 15:32 UTC, CyberTailor commented
Missed that! Fixed now (hopefully)

2023-02-06 18:00 UTC, AenBleidd commented
Still failing...

2023-02-06 23:25 UTC, AenBleidd commented
I believe I found the root cause of this issue.
I'll try to fix it separately.
For now I'll keep this PR open in case I'm wrong

2023-02-12 18:31 UTC, AenBleidd commented
Closing this in favor of #5096 that has a complete fix of the issue

2023-02-12 18:31 UTC, closed without merging