[Client][Manager] Support http2 connection, show IP and http version on manager
BOINC/boinc pull request #5102
Opened 2023-02-14 04:40 UTC by talregev

Add support http2 connection. Client can connect to the server and account manager in http2.
Show IP and http version on manager.

Currently World Community Grid and Boinc Account Manager are support http2.

2023-02-14 05:11 UTC, AenBleidd requested changes
While adding support of http2 to Windows build is generally fine, looks like no other OS is touched by this PR.

@talregev, does that mean that Linux, OSX and Android already have support of it and only in Windows build it was missed?

But in any case, this information is useless for the most of users, because it is usually static and don't represent anything that user can fix/improve.

2023-02-14 05:16 UTC, talregev commented
In this PR It effect Windows and Linux.
I can add to here for android without visible notice for the user. 
For Mac I will add support in following PR. 

It another info about server and transformation. Like the name of the project is static and user cannot effect it and many other information we display for the user.

2023-02-14 05:24 UTC, AenBleidd commented
> It another info about server and transformation. Like the name of the project is static and user cannot effect it and many other information we display for the user.

'Project Name' is static, that's true. But it shows to the user information what is the Project application tries to download/upload from/to. And in case smth stuck - user has possibility to contact the Project.
But neither http version not ip version don't give any valuable information that user could use in any way: project either support http2 or not, and if not - user can do nothing to change that. The same is about the ip version.
That is why this is useless information.

As you may remember, we try to keep UI as simple as possible and provide only valuable information to our users (and still some of them think it's to techy and it should be made simpler and less boring).
Adding http version and ip version (that most of the users have no idea what does that mean and what's the difference between them) overloads UI with information that is not needed.

I see no case when this information could be useful.

I'm sorry, but as a general advice: before starting to implement smth that has no open ticket - ask first, because there could be a reason (like this) why this feature is not welcome.

2023-02-14 05:27 UTC, talregev commented
User also can contact to Project and ask about planning to add support in http2 that can lead to stable transformations. 
Also without noticeable UI, you cannot test this feature easily. For example for android.

2023-02-14 09:18 UTC, talregev commented
Currently is not working on vcpkg Linux. I am not sure why. Can you test it on your side?

2023-02-14 12:48 UTC, AenBleidd commented
> Currently is not working on vcpkg Linux. I am not sure why. Can you test it on your side?

I don't think I have time for this right now.
Meanwhile it would be good if you:
- Verify that you don't have `http_1_0` set to `1` in your `cc_config.xml` file
- Set `http_debug` logging flag and provide logs

Also, you can temporary make `libcurl_exec()` function public and test it separately with debug logs enabled (from the previous point) and test download on some page with http2 support (e.g. http://www.http2demo.io/)

2023-02-28 15:02 UTC, talregev commented
> Currently is not working on vcpkg Linux. I am not sure why. Can you test it on your side?

I fix the bug.

2023-03-01 13:54 UTC, AenBleidd requested changes

2023-03-01 13:54 UTC, AenBleidd commented on client/pers_file_xfer.cpp
> +            "        <http_version>%s</http_version>\n"
These two lines are not needed, please remove

2023-03-01 13:54 UTC, AenBleidd commented on clientgui/ViewTransfers.cpp
> +#define COLUMN_HTTP_VERSION         8
These two lines are not needed, please remove

2023-03-01 13:54 UTC, AenBleidd commented on clientgui/ViewTransfers.cpp
> +                                COLUMN_STATUS, COLUMN_HTTP_VERSION, COLUMN_IP_VERSION};
This is not needed, please remove

2023-03-01 13:54 UTC, AenBleidd commented on clientgui/ViewTransfers.cpp
> +    m_strHttpVersion.Clear();
These two lines are not needed, please remove

2023-03-01 13:54 UTC, AenBleidd commented on clientgui/ViewTransfers.cpp
> +    case COLUMN_HTTP_VERSION:
These are not needed, please remove

2023-03-01 13:54 UTC, AenBleidd commented on clientgui/ViewTransfers.cpp
> +    m_aStdColNameOrder->Insert(_("HTTP Version"), COLUMN_HTTP_VERSION);
These two lines are not needed, please remove

2023-03-01 13:54 UTC, AenBleidd commented on clientgui/ViewTransfers.cpp
> +    m_iStdColWidthOrder.Insert(100, COLUMN_HTTP_VERSION);
These two lines are not needed, please remove

2023-03-01 13:54 UTC, AenBleidd commented on clientgui/ViewTransfers.cpp
> +        case COLUMN_HTTP_VERSION:
These are not needed. please remove

2023-03-01 13:54 UTC, AenBleidd commented on clientgui/ViewTransfers.cpp
> +        case COLUMN_HTTP_VERSION:
These are not needed, please remove

2023-03-01 13:54 UTC, AenBleidd commented on clientgui/ViewTransfers.cpp
> +        case COLUMN_HTTP_VERSION:
These are not needed, please remove

2023-03-01 13:54 UTC, AenBleidd commented on clientgui/ViewTransfers.cpp
> +void CViewTransfers::GetDocHTTPVersion(wxInt32 item, wxString& strBuffer) const {
This function is not needed, please remove

2023-03-01 13:54 UTC, AenBleidd commented on clientgui/ViewTransfers.cpp
> +void CViewTransfers::GetDocIPVersion(wxInt32 item, wxString& strBuffer) const {
This function is not needed, please remove

2023-03-01 13:54 UTC, AenBleidd commented on clientgui/ViewTransfers.h
> +    wxString m_strHttpVersion;
These two lines are not needed, please remove

2023-03-01 13:54 UTC, AenBleidd commented on clientgui/ViewTransfers.h
> +    void                    GetDocHTTPVersion(wxInt32 item, wxString& strBuffer) const;
These two functions are not needed, please remove

2023-03-01 13:54 UTC, AenBleidd commented on lib/gui_rpc_client.h
> +    std::string http_version;
These two lines are not needed, please remove

2023-03-01 13:54 UTC, AenBleidd commented on lib/gui_rpc_client_ops.cpp
> +        if (xp.parse_string("http_version", http_version)) continue;
These two lines are not needed, please remove

2023-03-01 13:54 UTC, AenBleidd commented on lib/gui_rpc_client_ops.cpp
> +    http_version.clear();
These two lines are not needed, please remove

2023-03-01 13:54 UTC, AenBleidd commented on lib/gui_rpc_client_print.cpp
> +    printf("   http_version: %s\n", http_version.c_str());
These two lines are not needed, please remove

2023-03-01 13:54 UTC, AenBleidd commented on linux/ci_configure_manager.sh
> +./configure --enable-vcpkg --disable-server --disable-client --with-wx-config=$VCPKG_DIR/tools/wxwidgets/wx-config GTK_LIBS="`pkg-config --libs gtk+-3.0`"
This looks like not related to this particular PR.
Please move it from here to a separate PR

2023-03-01 13:54 UTC, AenBleidd commented on client/http_curl.cpp
> +    phop->update_http_ip_version();
This function will write to the log file om every write call. This is not needed.
This should be written only once when connections is established

2023-03-01 13:54 UTC, AenBleidd commented on client/http_curl.cpp
> +    phop->update_http_ip_version();
This function will write to the log file om every read call. This is not needed.
This should be written only once when connections is established

2023-03-01 13:54 UTC, AenBleidd commented on client/http_curl.h
> +    char m_http_version[100];
This information not need to be stored, so please remove these two member variables

2023-03-01 13:54 UTC, AenBleidd commented on client/http_curl.cpp
> +    safe_strcpy(m_http_version, "");
No need to save this information, so please remove these two lines

2023-03-01 13:54 UTC, AenBleidd commented on client/http_curl.cpp
> +std::string get_http_version(int _enum) {
According to the documentation ( https://curl.se/libcurl/c/CURLINFO_HTTP_VERSION.html ) valid values are:
- CURL_HTTP_VERSION_1_0
- CURL_HTTP_VERSION_1_1
- CURL_HTTP_VERSION_2_0
- CURL_HTTP_VERSION_3
- or 0 if the version cannot be determined.

See no reason to check for other values

2023-03-01 13:54 UTC, AenBleidd commented on client/http_curl.cpp
> +        return "HTTP_ERROR";
Better to return `unknown http version`

2023-05-26 09:39 UTC, AenBleidd commented
As it was stated above, neither HTTP2 nor HTTP3 will bring a lot of benefit to the BOINC.
BOINC Client does not send a lot of requests to the servers, so latency is not an issue in our case.
Also, we're usually not sending several parallel requests to the server, and we're even doing max two concurrent file download/upload.

I'm closing this PR without merge.

2023-05-26 09:39 UTC, closed without merging